name: Build Godot

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y scons build-essential python3

      - name: Build
        run: |
          scons platform=linuxbsd target=editor -j2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: godot-linux
          path: bin/*
