name: Build Godot Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install SCons
        run: |
          pip install scons

      - name: Build Editor
        run: |
          scons platform=windows target=editor production=yes

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-windows
          path: bin/*
